//
//  DetailInterfaces.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/15.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DetailWireframeInterface: WireframeInterface {
}

protocol DetailViewInterface: ViewInterface {
    func updatePhotoList(section: Int)
}

protocol DetailPresenterInterface: PresenterInterface {
    func getCurrentPhotoSection() -> Int
    func getCurrentPhotoIndex() -> Int
    func getPhotoSectionList(for section: Int) -> [PhotoModel]
    func getSectionCount() -> Int
    func requestMorePhoto()

    func updateCurrentPosition(section: Int, index: Int)
    func passCurrentPhotoInfo()
}

protocol DetailInteractorInterface: InteractorInterface {
    func listPhotos(page: Int, completion: @escaping PhotoListCompletionHandler)
}
