//
//  DetailPresenter.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/15.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface

    // Main Module에 데이터를 전달하기 위한 delegate
    private weak var delegate: DelegatePresenterInterface?

    // MARK: - Lifecycle -

    init(delegate: DelegatePresenterInterface, view: DetailViewInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface) {
        self.delegate = delegate
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
}
