//
//  DetailViewController.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/15.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailViewController: UIViewController {

    @IBOutlet weak var detailCollectionView: UICollectionView!

    private let titleLabel: UILabel = {
        let titleLabel = UILabel()
        titleLabel.textAlignment = .center

        return titleLabel
    }()
    // MARK: - Public properties -

    var presenter: DetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()

        setupUI()
    }
}

// MARK: - Extensions -

extension DetailViewController: DetailViewInterface {
    func setupUI() {
        navigationItem.hidesBackButton = true

        let closeButton = UIBarButtonItem(image: UIImage(systemName: "xmark"), style: UIBarButtonItem.Style.plain, target: self, action: #selector(closeButtonTouched(sender:)))
        closeButton.tintColor = .black
        navigationItem.leftBarButtonItem = closeButton

        let detailCollectionViewLayout = UICollectionViewFlowLayout()

        detailCollectionViewLayout.scrollDirection = .horizontal
        detailCollectionViewLayout.itemSize = detailCollectionView.frame.size
        detailCollectionViewLayout.sectionInset = .zero
        detailCollectionViewLayout.minimumLineSpacing = .zero
        detailCollectionViewLayout.minimumInteritemSpacing = .zero

        detailCollectionView.setCollectionViewLayout(detailCollectionViewLayout, animated: false)
        detailCollectionView.isPagingEnabled = true
        detailCollectionView.alwaysBounceHorizontal = true
        detailCollectionView.showsHorizontalScrollIndicator = false


        detailCollectionView.delegate = self
        detailCollectionView.dataSource = self

        let bundle = Bundle(for: DetailPictureCell.self)
        let nib = UINib(nibName: String(describing: DetailPictureCell.self), bundle: bundle)

        detailCollectionView.register(nib, forCellWithReuseIdentifier: String(describing: DetailPictureCell.self))

        let currentPhotoSection = presenter.getCurrentPhotoSection()
        let currentPhotoIndex = presenter.getCurrentPhotoIndex()
        let currentPhotoItem = presenter.getPhotoSectionList(for: currentPhotoSection)[currentPhotoIndex]

        // Navigation Bar Title 작업
        changeTitle(name: currentPhotoItem.user.name, sponsorName: currentPhotoItem.sponsorship?.sponsor.name)

        detailCollectionView.reloadData()
        detailCollectionView.layoutIfNeeded()
        detailCollectionView.scrollToItem(at: IndexPath(item: currentPhotoIndex, section: currentPhotoSection), at: .centeredHorizontally, animated: false)
    }

    func updatePhotoList(section: Int) {
        self.detailCollectionView.insertSections(IndexSet(integer: section))
        self.detailCollectionView.layoutIfNeeded()
    }
}

// MARK: - Private Extensions -
private extension DetailViewController {
    @objc func closeButtonTouched(sender: UIBarButtonItem) {
        presenter.passCurrentPhotoInfo()
        navigationController?.popViewController(animated: true)
    }

    func changeTitle(name: String, sponsorName: String?) {
        titleLabel.numberOfLines = 1
        let navTitle = NSMutableAttributedString(string: name, attributes:[
                                                    NSAttributedString.Key.foregroundColor: UIColor.black,
                                                    NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 15.0)])

        if let sponsorName = sponsorName {
            titleLabel.numberOfLines = 2
            if sponsorName == name {
                navTitle.append(NSMutableAttributedString(string: "\nSponsored", attributes:[
                                                            NSAttributedString.Key.foregroundColor: UIColor.gray,
                                                            NSAttributedString.Key.font: UIFont.systemFont(ofSize: 12.0)]))
            } else {
                navTitle.append(NSMutableAttributedString(string: "\nSponsored by \(sponsorName)", attributes:[
                                                            NSAttributedString.Key.foregroundColor: UIColor.gray,
                                                            NSAttributedString.Key.font: UIFont.systemFont(ofSize: 12.0)]))
            }
        }
        titleLabel.attributedText = navTitle
        titleLabel.sizeToFit()

        self.navigationItem.titleView = titleLabel
    }
}

// MARK: - Extensions: UICollectionViewDelegate -
extension DetailViewController: UICollectionViewDelegate {
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {

        // Scroll Paging시 indexPath를 가져오는 부분이 문제가 있어 0.1초의 딜레이를 줌
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            guard let visibleCell = self.detailCollectionView.visibleCells.first,
                  let indexPath = self.detailCollectionView.indexPath(for: visibleCell) else { return }

            // Title 변경
            let currentPhotoItem = self.presenter.getPhotoSectionList(for: indexPath.section)[indexPath.item]
            self.changeTitle(name: currentPhotoItem.user.name, sponsorName: currentPhotoItem.sponsorship?.sponsor.name)

            // 현재 Position Update
            self.presenter.updateCurrentPosition(section: indexPath.section, index: indexPath.item)

            // 현재 조회된 Photo List보다 더 스크롤이 진행될 경우 다음 page 정보를 읽어온다.
            let maxSectionCount = self.presenter.getSectionCount()
            let photoInSectionCount = self.presenter.getPhotoSectionList(for: maxSectionCount - 1).count

            if (indexPath.section + 1) == maxSectionCount && indexPath.item > photoInSectionCount - 3 {
                self.presenter.requestMorePhoto()
            }
        }
    }
}

// MARK: - Extensions: UICollectionViewDataSource -
extension DetailViewController: UICollectionViewDataSource {
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return presenter.getSectionCount()
    }

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return presenter.getPhotoSectionList(for: section).count
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = detailCollectionView.dequeueReusableCell(withReuseIdentifier: String(describing: DetailPictureCell.self), for: indexPath) as! DetailPictureCell

        cell.photoItem = presenter.getPhotoSectionList(for: indexPath.section)[indexPath.item]

        return cell
    }
}

// MARK: - Extensions: UICollectionViewDelegateFlowLayout -
extension DetailViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return detailCollectionView.frame.size
    }
}
