//
//  DetailInteractor.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/15.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailInteractor {
    private let photoModelService = PhotoModelService.shared
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
    func listPhotos(page: Int, completion: @escaping PhotoListCompletionHandler) {
        photoModelService.getPhotoList(page: page, completion: completion)
    }
}
