//
//  DetailPresenter.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/15.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface

    private var currentPhotoSection: Int
    private var currentPhotoIndex: Int
    private var photoModels: [Int:[PhotoModel]]

    private var isRequestingPhoto: Bool = false
    
    // Main Module에 데이터를 전달하기 위한 delegate
    private weak var delegate: DelegatePresenterInterface?

    // MARK: - Lifecycle -

    init(delegate: DelegatePresenterInterface, view: DetailViewInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface, section: Int, index: Int, photoModels: [Int:[PhotoModel]]) {
        self.delegate = delegate
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.currentPhotoSection = section
        self.currentPhotoIndex = index
        self.photoModels = photoModels
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
    func getCurrentPhotoSection() -> Int {
        return currentPhotoSection
    }

    func getCurrentPhotoIndex() -> Int {
        return currentPhotoIndex
    }

    func getPhotoSectionList(for section: Int) -> [PhotoModel] {
        return photoModels[section] ?? [PhotoModel]()
    }

    func getSectionCount() -> Int {
        return photoModels.count
    }

    func requestMorePhoto() {
        if !isRequestingPhoto {
            isRequestingPhoto = true

            // 현재 Section의 갯수는 마지막 Section번호 - 1이므로, 현재 Section 갯수의 Section 번호를 요청한다.
            let sectionForRequest = photoModels.count

            // Unsplash API는 1페이지부터 유의미한 데이터가 존재하여 section + 1을 함. Section:0 -> Page:1
            interactor.listPhotos(page: sectionForRequest + 1) { (photoModel) in
                guard let photoModel = photoModel else { return }

                self.photoModels[sectionForRequest] = photoModel

                DispatchQueue.main.async {
                    self.view.updatePhotoList(section: sectionForRequest)
                    self.isRequestingPhoto = false
                }
            }
        }
    }

    func updateCurrentPosition(section: Int, index: Int) {
        self.currentPhotoSection = section
        self.currentPhotoIndex = index
    }

    func passCurrentPhotoInfo() {
        let currentPhotoInfo: [String : Any] = ["section": currentPhotoSection, "index": currentPhotoIndex, "photoModels": photoModels]
        delegate?.passData(sender: self, data: currentPhotoInfo)
    }
}
