//
//  MainTabViewController.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/17.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum TabItem: Int {
    case home
    case search
}

final class MainTabViewController: UITabBarController {

    // MARK: - Public properties -

    var presenter: MainTabPresenterInterface!

    lazy var mainViewController: UIViewController = {
        let mainNavController = UINavigationController(rootViewController: MainWireframe().viewController)
        mainNavController.tabBarItem = UITabBarItem(title: "Main", image: UIImage(systemName: "house"), selectedImage: UIImage(systemName: "house"))

        return mainNavController
    }()

    lazy var searchViewController: UIViewController = {
        let searchNavController = UINavigationController(rootViewController: SearchWireframe().viewController)
        searchNavController.tabBarItem = UITabBarItem(title: "Search", image: UIImage(systemName: "magnifyingglass"), selectedImage: UIImage(systemName: "magnifyingglass"))

        return searchNavController
    }()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()

        setupUI()
    }

    override func viewWillAppear(_ animated: Bool) {
        viewControllers = [mainViewController, searchViewController]
    }
}

// MARK: - Extensions -

extension MainTabViewController: MainTabViewInterface {
    func setupUI() {
        tabBar.tintColor = .black
    }

}
