//
//  MainTabPresenter.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/17.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainTabPresenter {

    // MARK: - Private properties -

    private unowned let view: MainTabViewInterface
    private let interactor: MainTabInteractorInterface
    private let wireframe: MainTabWireframeInterface

    // MARK: - Lifecycle -

    init(view: MainTabViewInterface, interactor: MainTabInteractorInterface, wireframe: MainTabWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MainTabPresenter: MainTabPresenterInterface {
}
