//
//  MainTabInteractor.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/17.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainTabInteractor {
}

// MARK: - Extensions -

extension MainTabInteractor: MainTabInteractorInterface {
}
