//
//  SearchInterfaces.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/17.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum SearchNavigationOption {
    case detail(DelegatePresenterInterface, Int, Int, [Int:[PhotoModel]])
}

protocol SearchWireframeInterface: WireframeInterface {
    func navigate(to option: SearchNavigationOption)
}

protocol SearchViewInterface: ViewInterface {
    func updateSearchHistory()
    func updateSearchList()
    func updateSearchList(section: Int)
    func updateSearchListWithPosition(currentSection: Int, currentIndex: Int)
}

protocol SearchPresenterInterface: PresenterInterface {
    func getSearchHistory() -> [SearchHistoryModel]
    func saveSearchHistory(searchText: String)
    func loadSearchHistory()
    func clearSearchHistory()

    func searchPhoto(searchText: String)
    func getSearchSection() -> Int
    func getSearchSectionList(for section: Int) -> [PhotoModel]
    func getSearchSectionCount() -> Int

    func moveToDetail(section: Int, index: Int)
    func requestMorePhoto(searchText: String)
    func clearSearch()
}

protocol SearchInteractorInterface: InteractorInterface {
    func saveSearchHistory(searchText: String)
    func loadSearchHistory() -> [SearchHistoryModel]
    func clearSearchHistory()
    func searchPhoto(page: Int, searchText: String, completion: @escaping PhotoListCompletionHandler)
}
