//
//  SearchInteractor.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/17.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SearchInteractor {
    private let photoModelService = PhotoModelService.shared
    private let searchHistoryService = SearchHistoryService.shared
}

// MARK: - Extensions -

extension SearchInteractor: SearchInteractorInterface {
    func saveSearchHistory(searchText: String) {
        searchHistoryService.saveSearchHistory(keyword: searchText)
    }

    func loadSearchHistory() -> [SearchHistoryModel] {
        return searchHistoryService.loadSearchHistory()
    }

    func clearSearchHistory() {
        searchHistoryService.clearSearchHistory()
    }

    func searchPhoto(page: Int, searchText: String, completion: @escaping PhotoListCompletionHandler) {
        photoModelService.searchPhoto(page: page, searchText: searchText, completion: completion)
    }
}
