//
//  MainPresenter.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/14.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainPresenter {

    // MARK: - Private properties -

    private unowned let view: MainViewInterface
    private let interactor: MainInteractorInterface
    private let wireframe: MainWireframeInterface

    private var topicSection: Int = 0
    private var topicSectionList: [Int:[TopicModel]] = .init()
    private var photoSection: Int = 0
    private var photoSectionList: [Int:[PhotoModel]] = .init()

    private var currentTopicIndex: Int = 0
    private var isRequestingPhoto: Bool = false

    // MARK: - Lifecycle -

    init(view: MainViewInterface, interactor: MainInteractorInterface, wireframe: MainWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MainPresenter: MainPresenterInterface {
    func viewDidLoad() {
        listTopic()
    }

    func getTopicSection() -> Int {
        return topicSection
    }

    func getTopicSectionList(for section: Int) -> [TopicModel] {
        return topicSectionList[section] ?? [TopicModel]()
    }

    func getTopicSectionCount() -> Int {
        return topicSectionList.count
    }

    func getPhotoSection() -> Int {
        return photoSection
    }

    func getPhotoSectionList(for section: Int) -> [PhotoModel] {
        return photoSectionList[section] ?? [PhotoModel]()
    }

    func getPhotoSectionCount() -> Int {
        return photoSectionList.count
    }

    func getCurrentTopicIndex() -> Int {
        return currentTopicIndex
    }

    func updateCurrentTopicIndex(index: Int) {
        guard var topicModel = self.topicSectionList[0] else { return }
        topicModel[currentTopicIndex].topicSelected = false
        topicModel[index].topicSelected = true

        currentTopicIndex = index

        photoSection = 0
        photoSectionList = .init()

        listPhoto(topicId: topicModel[currentTopicIndex].id) { (photoModel) in
            guard let photoModel = photoModel else { return }

            self.photoSectionList[self.photoSection] = photoModel

            DispatchQueue.main.async {
                self.view.updateTopicList()
                self.view.updatePhotoListWithPosition(currentSection: 0, currentIndex: 0)
                self.isRequestingPhoto = false
            }
        }
    }

    func moveToDetail(section: Int, index: Int) {
        wireframe.navigate(to: .detail(self, section, index, photoSectionList))
    }

    func requestMorePhoto() {
        guard let topicModel = self.topicSectionList[0] else { return }

        if !isRequestingPhoto {
            photoSection += 1
            listPhoto(topicId: topicModel[currentTopicIndex].id) { (photoModel) in
                guard let photoModel = photoModel else { return }

                self.photoSectionList[self.photoSection] = photoModel

                DispatchQueue.main.async {
                    self.view.updatePhotoList(section: self.photoSection)
                    self.isRequestingPhoto = false
                }
            }
        }
    }
}

private extension MainPresenter {
    func listTopic() {
        // Unsplash API는 1페이지부터 유의미한 데이터가 존재하여 section + 1을 함. Section:0 -> Page:1
        interactor.listTopics(page: topicSection + 1) { (topicModel) in
            guard var topicModel = topicModel else { return }

            topicModel[self.currentTopicIndex].topicSelected = true
            self.topicSectionList[self.topicSection] = topicModel
            self.view.updateTopicList()

            // 최초 Photo List 조회
            self.listPhoto(topicId: topicModel[self.currentTopicIndex].id) { (photoModel) in
                guard let photoModel = photoModel else { return }

                self.photoSectionList[self.photoSection] = photoModel

                DispatchQueue.main.async {
                    self.view.updatePhotoList()
                    self.isRequestingPhoto = false
                }
            }
        }
    }

    func listPhoto(topicId: String?, completion: @escaping PhotoListCompletionHandler) {
        isRequestingPhoto = true
        // Unsplash API는 1페이지부터 유의미한 데이터가 존재하여 section + 1을 함. Section:0 -> Page:1
        interactor.listPhotos(page: photoSection + 1, topicId: topicId, completion: completion)
    }
}

extension MainPresenter: DelegatePresenterInterface {
    func passData(sender: PresenterInterface, data: [String : Any]?) {
        switch sender {
        case is DetailPresenter:
            guard let data = data
                , let section = data["section"] as? Int
                , let index = data["index"] as? Int
                , let photoModels = data["photoModels"] as? [Int:[PhotoModel]] else { return }

            photoSectionList = photoModels

            DispatchQueue.main.async {
                self.view.updatePhotoListWithPosition(currentSection: section, currentIndex: index)
            }
        default:
            print("There is no defined sender.")
        }
    }
}
