//
//  MainWireframe.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/14.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: MainViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = MainInteractor()
        let presenter = MainPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MainWireframe: MainWireframeInterface {
    func navigate(to option: MainNavigationOption) {
        switch option {
        case .detail(let delegate):
            showDetail(delegate: delegate)
        }
    }

    func showDetail(delegate: DelegatePresenterInterface) {
        navigationController?.pushWireframe(DetailWireframe(delegate: delegate))
    }
}
