//
//  MainInterfaces.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/14.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MainNavigationOption {
    case detail(DelegatePresenterInterface)
}

protocol MainWireframeInterface: WireframeInterface {
    func navigate(to option: MainNavigationOption)
}

protocol MainViewInterface: ViewInterface {
}

protocol MainPresenterInterface: PresenterInterface {
    func moveToDetail()
}

protocol MainInteractorInterface: InteractorInterface {
}
