//
//  MainInteractor.swift
//  iOSCodeTest
//
//  Created by Joonghoo Im on 2021/04/14.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainInteractor {
    private let photoModelService = PhotoModelService.shared
    private let topicModelService = TopicModelService.shared
}

// MARK: - Extensions -

extension MainInteractor: MainInteractorInterface {
    func listTopics(page: Int, completion: @escaping TopicListCompletionHandler) {
        topicModelService.getTopicList(page: page, completion: completion)
    }
    
    func listPhotos(page: Int, completion: @escaping PhotoListCompletionHandler) {
        photoModelService.getPhotoList(page: page, completion: completion)
    }
}
